"""Adiciona a coluna linkedin_url em mentors

Revision ID: 277e8622070e
Revises: 1d858e440a75
Create Date: 2025-08-14 01:34:33.292822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277e8622070e'
down_revision: Union[str, Sequence[str], None] = '1d858e440a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('linkedin_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentors', 'linkedin_url')
    # ### end Alembic commands ###
